### ISSUE TITLE
TestBasic hangs

### ISSUE THREAD

**Issue by mvdan** [libp2p/zeroconf#21]
```
$ go test -timeout=5s ./...
2021/12/20 13:07:22 Published service: test--xxxxxxxxxxxx, type: _test--xxxx._tcp, domain: local.
panic: test timed out after 5s

goroutine 26 [running]:
testing.(*M).startAlarm.func1()
	/usr/lib/go/src/testing/testing.go:1788 +0x8e
created by time.goFunc
	/usr/lib/go/src/time/sleep.go:180 +0x31

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00008ba00, {0x5bd70d, 0x469d53}, 0x5c99d0)
	/usr/lib/go/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc00008ba00)
	/usr/lib/go/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc00008ba00, 0xc0000b7d18)
	/usr/lib/go/src/testing/testing.go:1259 +0x102
testing.runTests(0xc000108000, {0x706960, 0x4, 0x4}, {0x4798cd, 0x5bee77, 0x70b480})
	/usr/lib/go/src/testing/testing.go:1596 +0x43f
testing.(*M).Run(0xc000108000)
	/usr/lib/go/src/testing/testing.go:1504 +0x51d
main.main()
	_testmain.go:49 +0x14b

goroutine 5 [select]:
github.com/libp2p/zeroconf/v2.(*client).periodicQuery(0x5f7868, {0x5f77f8, 0xc000013e00}, 0xc0001a03c0)
	/home/mvdan/git/zeroconf/client.go:380 +0x193
github.com/libp2p/zeroconf/v2.(*client).run(0xc0001911a0, {0x5f7868, 0xc00007c060}, 0xc0001a03c0)
	/home/mvdan/git/zeroconf/client.go:121 +0x10d
github.com/libp2p/zeroconf/v2.Browse({0x5f7868, 0xc00007c060}, {0x5bf3da, 0x10}, {0x5bcc96, 0x6}, 0xc00007c120, {0x0, 0x0, 0x0})
	/home/mvdan/git/zeroconf/client.go:78 +0x132
github.com/libp2p/zeroconf/v2.TestBasic(0xc0000016c0)
	/home/mvdan/git/zeroconf/service_test.go:55 +0x117
testing.tRunner(0xc0000016c0, 0x5c99d0)
	/usr/lib/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1306 +0x35a

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f75269f8040, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000022880, 0x1, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).RawRead(0xc000022880, 0xc0001520c0)
	/usr/lib/go/src/internal/poll/fd_unix.go:554 +0x145
net.(*rawConn).Read(0xc000010030, 0x28)
	/usr/lib/go/src/net/rawconn.go:43 +0x45
golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc0000702a0, 0xc000316ee8, 0x0)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/rawconn_msg.go:33 +0x202
golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/socket.go:247
golang.org/x/net/ipv6.(*payloadHandler).ReadFrom(0xc00007e5b0, {0xc000300000, 0x10000, 0x10000})
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/ipv6/payload_cmsg.go:32 +0x1fc
github.com/libp2p/zeroconf/v2.(*Server).recv6(0xc00007c0c0, 0xc00007e5a0)
	/home/mvdan/git/zeroconf/server.go:270 +0xc7
created by github.com/libp2p/zeroconf/v2.(*Server).start
	/home/mvdan/git/zeroconf/server.go:189 +0x125

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7f75269f7f58, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000022800, 0x1, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).RawRead(0xc000022800, 0xc000191740)
	/usr/lib/go/src/internal/poll/fd_unix.go:554 +0x145
net.(*rawConn).Read(0xc000010020, 0x20)
	/usr/lib/go/src/net/rawconn.go:43 +0x45
golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc000070280, 0xc00005eee8, 0x0)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/rawconn_msg.go:33 +0x202
golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/socket.go:247
golang.org/x/net/ipv4.(*payloadHandler).ReadFrom(0xc00007e560, {0xc00012e000, 0x10000, 0x10000})
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/ipv4/payload_cmsg.go:32 +0x1ce
github.com/libp2p/zeroconf/v2.(*Server).recv4(0xc00007c0c0, 0xc00007e550)
	/home/mvdan/git/zeroconf/server.go:245 +0xc7
created by github.com/libp2p/zeroconf/v2.(*Server).start
	/home/mvdan/git/zeroconf/server.go:185 +0x9d

goroutine 9 [select]:
github.com/libp2p/zeroconf/v2.(*client).mainloop(0xc0001911a0, {0x5f77f8, 0xc000013e00}, 0xc0001a03c0)
	/home/mvdan/git/zeroconf/client.go:185 +0x3c5
github.com/libp2p/zeroconf/v2.(*client).run.func1()
	/home/mvdan/git/zeroconf/client.go:116 +0x68
created by github.com/libp2p/zeroconf/v2.(*client).run
	/home/mvdan/git/zeroconf/client.go:114 +0xf4

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f75269f7e70, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000022e00, 0xc00032a420, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).RawRead(0xc000022e00, 0xc000324510)
	/usr/lib/go/src/internal/poll/fd_unix.go:554 +0x145
net.(*rawConn).Read(0xc000010048, 0x20)
	/usr/lib/go/src/net/rawconn.go:43 +0x45
golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc000070c60, 0xc00005fe50, 0x0)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/rawconn_msg.go:33 +0x202
golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/socket.go:247
golang.org/x/net/ipv4.(*payloadHandler).ReadFrom(0xc00007e740, {0xc0001ca000, 0x10000, 0x10000})
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/ipv4/payload_cmsg.go:32 +0x1ce
github.com/libp2p/zeroconf/v2.(*client).recv.func2({0xc0001ca000, 0xc00005ff28, 0xcf})
	/home/mvdan/git/zeroconf/client.go:326 +0x34
github.com/libp2p/zeroconf/v2.(*client).recv(0xc000013e00, {0x5f77f8, 0xc000013e00}, {0x5b7500, 0xc00007e730}, 0xc0000ac5a0)
	/home/mvdan/git/zeroconf/client.go:345 +0x151
created by github.com/libp2p/zeroconf/v2.(*client).mainloop
	/home/mvdan/git/zeroconf/client.go:171 +0x154

goroutine 25 [IO wait]:
internal/poll.runtime_pollWait(0x7f75269f7d88, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000022e80, 0xc0002a32c0, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).RawRead(0xc000022e80, 0xc0002a86f0)
	/usr/lib/go/src/internal/poll/fd_unix.go:554 +0x145
net.(*rawConn).Read(0xc000010058, 0x28)
	/usr/lib/go/src/net/rawconn.go:43 +0x45
golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc000070c80, 0xc000312e50, 0x0)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/rawconn_msg.go:33 +0x202
golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/internal/socket/socket.go:247
golang.org/x/net/ipv6.(*payloadHandler).ReadFrom(0xc00007e790, {0xc000140000, 0x10000, 0x10000})
	/home/mvdan/go/pkg/mod/golang.org/x/net@v0.0.0-20210423184538-5f58ad60dda6/ipv6/payload_cmsg.go:32 +0x1fc
github.com/libp2p/zeroconf/v2.(*client).recv.func1({0xc000140000, 0xc000312f28, 0xcf})
	/home/mvdan/git/zeroconf/client.go:321 +0x34
github.com/libp2p/zeroconf/v2.(*client).recv(0x0, {0x5f77f8, 0xc000013e00}, {0x5b8000, 0xc00007e780}, 0xc0000ac5a0)
	/home/mvdan/git/zeroconf/client.go:345 +0x151
created by github.com/libp2p/zeroconf/v2.(*client).mainloop
	/home/mvdan/git/zeroconf/client.go:174 +0x245
FAIL	github.com/libp2p/zeroconf/v2	5.008s
?   	github.com/libp2p/zeroconf/v2/examples/proxyservice	[no test files]
?   	github.com/libp2p/zeroconf/v2/examples/register	[no test files]
?   	github.com/libp2p/zeroconf/v2/examples/resolv	[no test files]
FAIL
```

I initially thought this was due to my network, but I killed wifi and ensured `ip route` was empty, and it still hung.

Found while trying to debug https://github.com/libp2p/zeroconf/pull/20#issuecomment-992395815.

**Comment by mvdan** [comment]
I should have clarified this is `go version go1.17.5 linux/amd64` on 92498dabf5ddc3bb3568c9e6b61aa550ec81294d.
